$entries = @(
  @{ Name = 'Deccan Herald'; Domain = 'deccanherald.com'; File = 'deccan-herald.png' },
  @{ Name = 'The Statesman'; Domain = 'thestatesman.com'; File = 'the-statesman.png' },
  @{ Name = 'The Times of India'; Domain = 'timesofindia.indiatimes.com'; File = 'the-times-of-india.png' },
  @{ Name = 'The Economic Times'; Domain = 'economictimes.indiatimes.com'; File = 'the-economic-times.png' },
  @{ Name = 'Business Standard'; Domain = 'business-standard.com'; File = 'business-standard.png' },
  @{ Name = 'Financial Express'; Domain = 'financialexpress.com'; File = 'financial-express.png' },
  @{ Name = 'The Hindu'; Domain = 'thehindu.com'; File = 'the-hindu.png' },
  @{ Name = 'The Indian Express'; Domain = 'indianexpress.com'; File = 'the-indian-express.png' },
  @{ Name = 'The Print'; Domain = 'theprint.in'; File = 'the-print.png' },
  @{ Name = 'The Tribune'; Domain = 'tribuneindia.com'; File = 'the-tribune.png' },
  @{ Name = 'Amar Ujala'; Domain = 'amarujala.com'; File = 'amar-ujala.png' },
  @{ Name = 'Dainik Bhaskar'; Domain = 'bhaskar.com'; File = 'dainik-bhaskar.png' },
  @{ Name = 'Lokmat Times'; Domain = 'lokmattimes.com'; File = 'lokmat-times.png' },
  @{ Name = 'The Daily Guardian'; Domain = 'thedailyguardian.com'; File = 'the-daily-guardian.png' },
  @{ Name = 'Shah Times'; Domain = 'shahtimesnews.com'; File = 'shah-times.png' },
  @{ Name = 'Amrit India'; Domain = 'amritindia.co.in'; File = 'amrit-india.png' },
  @{ Name = 'ANI'; Domain = 'aninews.in'; File = 'ani.png' },
  @{ Name = 'PTI'; Domain = 'ptinews.com'; File = 'pti.png' },
  @{ Name = 'IANS'; Domain = 'ians.in'; File = 'ians.png' },
  @{ Name = 'UNI'; Domain = 'uniindia.com'; File = 'uni.png' },
  @{ Name = 'BW BusinessWorld'; Domain = 'businessworld.in'; File = 'bw-businessworld.png' },
  @{ Name = 'Outlook Business'; Domain = 'outlookbusiness.com'; File = 'outlook-business.png' },
  @{ Name = 'Zee Business'; Domain = 'zeebiz.com'; File = 'zee-business.png' },
  @{ Name = 'CXO Today'; Domain = 'cxotoday.com'; File = 'cxo-today.png' },
  @{ Name = 'Startup News'; Domain = 'startupnews.fyi'; File = 'startup-news.png' },
  @{ Name = 'India Economic Observer'; Domain = 'indiaeconomicobserver.com'; File = 'india-economic-observer.png' },
  @{ Name = 'India Defence News'; Domain = 'indiadefencenews.com'; File = 'india-defence-news.png' },
  @{ Name = 'MSN'; Domain = 'msn.com'; File = 'msn.png' },
  @{ Name = 'Latestly'; Domain = 'latestly.com'; File = 'latestly.png' },
  @{ Name = 'Awaz the Voice'; Domain = 'awazthevoice.in'; File = 'awaz-the-voice.png' },
  @{ Name = 'OmmCom News'; Domain = 'ommcomnews.com'; File = 'ommcom-news.png' },
  @{ Name = 'Social News XYZ'; Domain = 'socialnews.xyz'; File = 'social-news-xyz.png' },
  @{ Name = 'The Assam Tribune'; Domain = 'assamtribune.com'; File = 'the-assam-tribune.png' },
  @{ Name = 'The Shillong Times'; Domain = 'theshillongtimes.com'; File = 'the-shillong-times.png' },
  @{ Name = 'The News Mill'; Domain = 'thenewsmill.com'; File = 'the-news-mill.png' },
  @{ Name = 'Daily Excelsior'; Domain = 'dailyexcelsior.com'; File = 'daily-excelsior.png' },
  @{ Name = 'Jammu Links News'; Domain = 'jammulinksnews.com'; File = 'jammu-links-news.png' },
  @{ Name = 'The Better Andhra'; Domain = 'thebetterandhra.com'; File = 'the-better-andhra.png' },
  @{ Name = 'Suryaa'; Domain = 'suryaa.com'; File = 'suryaa.png' },
  @{ Name = 'The Hans India'; Domain = 'thehansindia.com'; File = 'the-hans-india.png' },
  @{ Name = 'Sakshi'; Domain = 'sakshi.com'; File = 'sakshi.png' },
  @{ Name = 'Sakshi Post'; Domain = 'sakshipost.com'; File = 'sakshi-post.png' },
  @{ Name = 'Punjab News Express'; Domain = 'punjabnewsexpress.com'; File = 'punjab-news-express.png' },
  @{ Name = 'Morung Express'; Domain = 'morungexpress.com'; File = 'morung-express.png' },
  @{ Name = 'Big News Network'; Domain = 'bignewsnetwork.com'; File = 'big-news-network.png' },
  @{ Name = 'New Kerala'; Domain = 'newkerala.com'; File = 'new-kerala.png' },
  @{ Name = 'City Air News'; Domain = 'cityairnews.com'; File = 'city-air-news.png' },
  @{ Name = 'Desi Talk in Chicago'; Domain = 'desitalkchicago.com'; File = 'desi-talk-in-chicago.png' },
  @{ Name = 'India Post'; Domain = 'indiapost.com'; File = 'india-post.png' },
  @{ Name = 'Indian Community'; Domain = 'indiancommunity.com'; File = 'indian-community.png' },
  @{ Name = 'Malaysia Sun'; Domain = 'malaysiasun.com'; File = 'malaysia-sun.png' },
  @{ Name = 'Web India'; Domain = 'webindia123.com'; File = 'web-india.png' },
  @{ Name = 'ChiniMandi'; Domain = 'chinimandi.com'; File = 'chini-mandi.png' },
  @{ Name = 'Newsgram'; Domain = 'newsgram.com'; File = 'newsgram.png' },
  @{ Name = 'Swadesi'; Domain = 'swadesi.com'; File = 'swadesi.png' },
  @{ Name = 'News Nation'; Domain = 'newsnationnow.com'; File = 'news-nation.png' },
  @{ Name = 'News Mobile'; Domain = 'newsmobile.in'; File = 'news-mobile.png' },
  @{ Name = 'Naveen Times'; Domain = 'naveentimes.in'; File = 'naveen-times.png' },
  @{ Name = 'AP7AM'; Domain = 'ap7am.com'; File = 'ap7am.png' },
  @{ Name = 'The Hawk'; Domain = 'thehawk.in'; File = 'the-hawk.png' },
  @{ Name = 'Ten News'; Domain = 'tennews.in'; File = 'ten-news.png' },
  @{ Name = 'Yugmarg'; Domain = 'yugmarg.com'; File = 'yugmarg.png' },
  @{ Name = 'New Delhi Times'; Domain = 'newdelhitimes.com'; File = 'new-delhi-times.png' },
  @{ Name = 'WN'; Domain = 'wn.com'; File = 'wn.png' },
  @{ Name = 'DD News'; Domain = 'ddnews.gov.in'; File = 'dd-news.png' },
  @{ Name = 'DD India'; Domain = 'ddindia.gov.in'; File = 'dd-india.png' },
  @{ Name = 'News On Air'; Domain = 'newsonair.gov.in'; File = 'news-on-air.png' },
  @{ Name = 'India Today Global'; Domain = 'indiatoday.in'; File = 'india-today-global.png' },
  @{ Name = 'ABP News'; Domain = 'abplive.com'; File = 'abp-news.png' },
  @{ Name = 'The Mojo Story'; Domain = 'themojostory.com'; File = 'the-mojo-story.png' },
  @{ Name = 'Jansatta'; Domain = 'jansatta.com'; File = 'jansatta.png' },
  @{ Name = 'CVR English Official'; Domain = 'cvrenglish.com'; File = 'cvr-english-official.png' },
  @{ Name = 'Ministry of External Affairs'; Domain = 'mea.gov.in'; File = 'ministry-of-external-affairs.png' }
)

$entries | ConvertTo-Json -Depth 2 | Set-Content -Path 'c:\Users\Media\Desktop\New folder\Media House\media-house-domains.json' -Encoding UTF8
